// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnubweogzsnkbscxpphp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudWJ3ZW9nenNua2JzY3hwcGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTA2MDcsImV4cCI6MjA3MjQ4NjYwN30._PDr_U0ZuYF_iIjtiRp3MtIZYZbPMjyu1vcDctjWO_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});